### ISSUE TITLE
github.com/jboverfelt/hs fails to clone

### ISSUE THREAD

**Issue by jboverfelt** [driusan/dgit#190]
Hi! Thanks for your work on this - it's been very helpful on systems where it's easier to cross-compile Go than Git! I've run into an issue where cloning a particular repository causes a panic. 

What I Did: `dgit clone https://github.com/jboverfelt/hs`

What I Expected: The repository to be cloned

What Happened Instead:

```
Initialized empty Git repository in /home/joverfelt/hs/.git/
remote: Enumerating objects: 97, done.
Counting objects: 100% (97remote: /97), done.
remote: Compressing objects: 100% (71/71), done.
Indexing objects: 100% (97/97)panic: unexpected EOF

goroutine 1 [running]:
github.com/driusan/dgit/git.PackfileHeader.readEntryDataStream1(0x0, 0xc000000000, 0x869620, 0xc0003c7620, 0x0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/packfile.go:163 +0x172
github.com/driusan/dgit/git.PackfileIndexV2.getObjectAtOffset(0x2634f74ff, 0x200000001, 0x200000002, 0x200000002, 0x400000003, 0x400000004, 0x400000004, 0x500000004, 0x600000005, 0x700000006, ...)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/indexpack.go:142 +0x1f6
github.com/driusan/dgit/git.(*Client).getPackedObject(0xc000090360, 0xc000076600, 0x52, 0x3416c057414fbaa6, 0x9aaa4a3d88a98ed7, 0x7a8c39f7, 0x0, 0x0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/objects.go:189 +0x1ff
github.com/driusan/dgit/git.(*Client).getObject(0xc000090360, 0x3416c057414fbaa6, 0x9aaa4a3d88a98ed7, 0x7a8c39f7, 0x0, 0x0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/objects.go:229 +0x1c6
github.com/driusan/dgit/git.(*Client).GetObject(0xc000090360, 0x3416c057414fbaa6, 0x9aaa4a3d88a98ed7, 0xc07a8c39f7, 0x0, 0x6, 0x0, 0xc0003c7470)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/objects.go:209 +0x44
github.com/driusan/dgit/git.expandGitTreeIntoIndexesRecursive(0xc000090360, 0xae4e9f0981723150, 0xe9c9c6a5f643975f, 0xc03192f353, 0x0, 0x0, 0x31000001, 0x0, 0x0, 0xae0900, ...)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/expandtree.go:66 +0x561
github.com/driusan/dgit/git.expandGitTreeIntoIndexes(0xc000090360, 0x869f80, 0xc00008d3c0, 0xc000000001, 0x40db88, 0x30, 0x7c3740, 0x10dadd01, 0xc0003c7290)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/expandtree.go:30 +0x166
github.com/driusan/dgit/git.(*Index).ResetIndex(0xc0003c7290, 0xc000090360, 0x869f80, 0xc00008d3c0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/index.go:689 +0x4f
github.com/driusan/dgit/git.ReadTree(0xc000090360, 0x10100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x869f80, ...)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/readtree.go:618 +0x387
github.com/driusan/dgit/git.ResetMode(0xc000090360, 0x1000000, 0x869f60, 0xc00008d0a0, 0x0, 0x0)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/reset.go:124 +0x29e
github.com/driusan/dgit/git.Reset(0xc000090360, 0x1000000, 0x0, 0x0, 0x0, 0xb1, 0x2b1)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/reset.go:64 +0x827
github.com/driusan/dgit/git.Clone(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, ...)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/git/clone.go:135 +0x9e8
github.com/driusan/dgit/cmd.Clone(0x0, 0xc000082080, 0x1, 0x1, 0xffffffffffffffff, 0x869480)
	/home/joverfelt/gospace/src/github.com/driusan/dgit/cmd/clone.go:60 +0x52a
main.main()
	/home/joverfelt/gospace/src/github.com/driusan/dgit/main.go:199 +0x440b
```

I was able to reproduce this on both netbsd/amd64 and linux/amd64. I should note that I can't find another repository that causes this issue. BTW, I'll be sending a PR for some minor netbsd syscall fixes unrelated to this issue.

**Comment by driusan** [comment]
Should be fixed now (I was able to clone it with the latest commit on DragonFly, but the underlying issue wasn't OS specific..)

Thanks for reporting this

**Comment by jboverfelt** [comment]
Just tested with the hs repo - works great! Thanks for fixing it so quickly!
