### ISSUE TITLE
Hang on git write-tree

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#24]
While attempting a write-tree command, such as ```dgit write-tree --prefix=path3``` I encountered a hang. The dgit process consumes a lot of CPU and begins consume a lot of memory. Here is the stack trace I was able to obtain using the "kill -ABRT" trick:

```
goroutine 1 [runnable]:
strings.Split(0xc420016510, 0xb, 0x133475d, 0x1, 0x1, 0xc70014e000, 0x4dd84)
	/usr/local/go/src/strings/strings.go:298 +0x8e
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc700076000, 0x4dd83, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:73 +0x1d3
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6ffdee000, 0x4dd7d, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6ffb66000, 0x4dd77, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6ff8de000, 0x4dd71, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6ff656000, 0x4dd6b, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6ff3ce000, 0x4dd65, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6ff146000, 0x4dd5f, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6feebe000, 0x4dd59, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fec36000, 0x4dd53, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fe9ae000, 0x4dd4d, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fe726000, 0x4dd47, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fe49e000, 0x4dd41, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fe216000, 0x4dd3b, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fdf8e000, 0x4dd35, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fdd06000, 0x4dd2f, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fda7e000, 0x4dd29, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fd7f6000, 0x4dd23, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fd56e000, 0x4dd1d, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fd2e6000, 0x4dd17, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fd05e000, 0x4dd11, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fcdd6000, 0x4dd0b, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fcb4e000, 0x4dd05, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fc8c6000, 0x4dcff, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fc63e000, 0x4dcf9, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fc3b6000, 0x4dcf3, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fc12e000, 0x4dced, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fbea6000, 0x4dce7, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fbc1e000, 0x4dce1, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fb996000, 0x4dcdb, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fb70e000, 0x4dcd5, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fb486000, 0x4dccf, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fb1fe000, 0x4dcc9, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6faf76000, 0x4dcc3, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6facee000, 0x4dcbd, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6faa66000, 0x4dcb7, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fa7de000, 0x4dcb1, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fa556000, 0x4dcab, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fa2ce000, 0x4dca5, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6fa046000, 0x4dc9f, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f9dbe000, 0x4dc99, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f9b36000, 0x4dc93, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f98ae000, 0x4dc8d, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f9626000, 0x4dc87, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f939e000, 0x4dc81, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f9116000, 0x4dc7b, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f8e8e000, 0x4dc75, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f8c06000, 0x4dc6f, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f897e000, 0x4dc69, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f86f6000, 0x4dc63, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f846e000, 0x4dc5d, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f81e6000, 0x4dc57, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f7f5e000, 0x4dc51, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f7cd6000, 0x4dc4b, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f7a4e000, 0x4dc45, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f77c6000, 0x4dc3f, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f753e000, 0x4dc39, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f72b6000, 0x4dc33, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f702e000, 0x4dc2d, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f6da6000, 0x4dc27, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f6b1e000, 0x4dc21, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f6896000, 0x4dc1b, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f660e000, 0x4dc15, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f6386000, 0x4dc0f, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f60fe000, 0x4dc09, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f5e76000, 0x4dc03, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f5bee000, 0x4dbfd, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f5966000, 0x4dbf7, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f56de000, 0x4dbf1, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f5456000, 0x4dbeb, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f51ce000, 0x4dbe5, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f4f46000, 0x4dbdf, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f4cbe000, 0x4dbd9, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f4a36000, 0x4dbd3, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f47ae000, 0x4dbcd, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f4526000, 0x4dbc7, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f429e000, 0x4dbc1, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f4016000, 0x4dbbb, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f3d8e000, 0x4dbb5, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f3b06000, 0x4dbaf, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f387e000, 0x4dba9, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f35f6000, 0x4dba3, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f336e000, 0x4db9d, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f30e6000, 0x4db97, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f2e5e000, 0x4db91, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f2bd6000, 0x4db8b, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f294e000, 0x4db85, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f26c6000, 0x4db7f, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f243e000, 0x4db79, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f21b6000, 0x4db73, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f1f2e000, 0x4db6d, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f1ca6000, 0x4db67, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f1a1e000, 0x4db61, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f1796000, 0x4db5b, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f150e000, 0x4db55, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f1286000, 0x4db4f, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f0ffe000, 0x4db49, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f0d76000, 0x4db43, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f0aee000, 0x4db3d, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
github.com/driusan/dgit/git.writeTree(0xc420010db0, 0xc6f0870000, 0x4db37, 0xc42010c340, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1270467, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/writetree.go:139 +0x317
...additional frames elided...
```

**Comment by sirnewton01** [comment]
I have attached the repo where I see the hang.

[badrepo.zip](https://github.com/driusan/dgit/files/2180440/badrepo.zip)

**Comment by driusan** [comment]
Looks like an infinite loop. Is the repo from the git test suite or one that you created organically?

**Comment by sirnewton01** [comment]
I enabled an fmt.Printf statement that was commented out in git/writetree.go. It's getting stuck like this:

```
This name: path0
This name: path2/file2
This name: file3
This name: path2/file2
This name: path2/file2
This name: path2/file2
This name: path2/file2
This name: path2/file2
This name: path2/file2
...
```

Also, the recursion seems to be in a section where it says that it has found the end of the tree, it's just trying to get the SHA-1 hash.

**Comment by sirnewton01** [comment]
It's recursing on line [139](https://github.com/driusan/dgit/blob/4a677c7c8c1e54e0d80e520dc3b6f06f088bd055/git/writetree.go#L139) but before it gets there it is hitting line [125](https://github.com/driusan/dgit/blob/4a677c7c8c1e54e0d80e520dc3b6f06f088bd055/git/writetree.go#L125)

**Comment by driusan** [comment]
What are prefix and newprefix at line 139? Line 125 is supposed to ensure that at least 1 part of the path is always stripped off to prevent this loop. And in the index are there 1 or more than 1 files under path2? `git ls-files -c -s` will tell you exactly what's in the index that it's trying to convert into a tree.

**Comment by driusan** [comment]
```
100644 f87290f8eb2cbbea7857214459a0739927eab154 0	path0
100644 3feff949ed00a62d9f7af97c15cd8a30595e7ac7 0	path2/file2
100644 0aa34cae68d0878578ad119c86ca2b5ed5b28376 0	path3/file3
100644 00fb5908cb97c2564a9783c0c64087333b3b464f 0	path3/subp3/file3
```

**Comment by sirnewton01** [comment]
Here's what I get when I dump prefix and new prefix at line 139:

prefix: path3/path2 newprefix: path3/path2/path2
prefix: path3/path2/path2 newprefix: path3/path2/path2/path2
prefix: path3/path2/path2/path2 newprefix: path3/path2/path2/path2/path2
...

**Comment by driusan** [comment]
That took longer than I care to admit for a fix that ended up being trivial, but I added test cases for this now, and it seems to be good.
