### ISSUE TITLE
Hang on dgit rev-list

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#25]
When I perform a rev-list on a particular git repo dgit just hangs there consuming the CPU.

```
$ dgit rev-list HEAD
```

When I use the kill -ABRT trick after letting it run for a minute I get this information.

```
SIGABRT: abort
PC=0x1073e76 m=0 sigcode=0

goroutine 1 [syscall]:
syscall.Syscall(0x3, 0x3, 0xc423a50f38, 0x4, 0xc420000180, 0xc420020140, 0xc423c33bd8)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5 fp=0xc423c33b78 sp=0xc423c33b70 pc=0x1073e45
syscall.read(0x3, 0xc423a50f38, 0x4, 0x8, 0xc420020101, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:947 +0x5f fp=0xc423c33bd8 sp=0xc423c33b78 pc=0x107314f
syscall.Read(0x3, 0xc423a50f38, 0x4, 0x8, 0x4, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:162 +0x49 fp=0xc423c33c20 sp=0xc423c33bd8 pc=0x1070de9
internal/poll.(*FD).Read(0xc4200ac820, 0xc423a50f38, 0x4, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:153 +0x116 fp=0xc423c33c70 sp=0xc423c33c20 pc=0x1085896
os.(*File).read(0xc4200aa038, 0xc423a50f38, 0x4, 0x8, 0x4, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:226 +0x4e fp=0xc423c33cb8 sp=0xc423c33c70 pc=0x108ae0e
os.(*File).Read(0xc4200aa038, 0xc423a50f38, 0x4, 0x8, 0x8, 0x0, 0x0)
	/usr/local/go/src/os/file.go:107 +0x6a fp=0xc423c33d28 sp=0xc423c33cb8 pc=0x1088d0a
io.ReadAtLeast(0x13749e0, 0xc4200aa038, 0xc423a50f38, 0x4, 0x8, 0x4, 0x12ceac0, 0x1, 0xc423a50f38)
	/usr/local/go/src/io/io.go:309 +0x86 fp=0xc423c33d88 sp=0xc423c33d28 pc=0x106b186
io.ReadFull(0x13749e0, 0xc4200aa038, 0xc423a50f38, 0x4, 0x8, 0x4, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58 fp=0xc423c33de0 sp=0xc423c33d88 pc=0x106b2f8
encoding/binary.Read(0x13749e0, 0xc4200aa038, 0x1378d20, 0x14f43b0, 0x12bdd60, 0xc421a0b5f4, 0x0, 0x0)
	/usr/local/go/src/encoding/binary/binary.go:171 +0xe5 fp=0xc423c33f38 sp=0xc423c33de0 pc=0x1104785
github.com/driusan/dgit/git.getPackFileObject(0x13749e0, 0xc4200aa038, 0x1376a80, 0xc4200aa040, 0xb6f0f479ed814309, 0xf62f20a12d50307f, 0x45162627, 0xc423c344d8, 0x1012368, 0x20, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/indexpack.go:241 +0x3bc fp=0xc423c34470 sp=0xc423c33f38 pc=0x124950c
github.com/driusan/dgit/git.(*Client).getPackedObject(0xc42009adb0, 0xc42008c2a0, 0x55, 0xb6f0f479ed814309, 0xf62f20a12d50307f, 0xc445162627, 0x0, 0x0, 0x0, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/objects.go:156 +0x1a0 fp=0xc423c344e8 sp=0xc423c34470 pc=0x1254c90
github.com/driusan/dgit/git.(*Client).GetObject(0xc42009adb0, 0xb6f0f479ed814309, 0xf62f20a12d50307f, 0x45162627, 0x0, 0x0, 0x0, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/objects.go:179 +0xe25 fp=0xc423c347f0 sp=0xc423c344e8 pc=0x1255d55
github.com/driusan/dgit/git.CommitID.Parents(0xb6f0f479ed814309, 0xf62f20a12d50307f, 0xc445162627, 0xc42009adb0, 0x0, 0x8, 0xc423c349d7, 0x1, 0x1)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:116 +0x5d fp=0xc423c34970 sp=0xc423c347f0 pc=0x1262cdd
github.com/driusan/dgit/git.CommitID.ancestors(0xb6f0f479ed814309, 0xf62f20a12d50307f, 0x45162627, 0xc42009adb0, 0x1, 0xc42065c0c0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:350 +0xc3 fp=0xc423c34b08 sp=0xc423c34970 pc=0x12649c3
github.com/driusan/dgit/git.CommitID.ancestors(0xef695d7b2881fffa, 0xcc19392de28d4014, 0x6acf07f, 0xc42009adb0, 0x1, 0xc421e684c0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c34ca0 sp=0xc423c34b08 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xc4782e4875099c92, 0xc6ea8c0a010b68bd, 0xa06011c3, 0xc42009adb0, 0x1, 0xc4239905c0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c34e38 sp=0xc423c34ca0 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xea4fbc4ed63224f7, 0x7bdb4d4614512680, 0x3396ce25, 0xc42009adb0, 0x1, 0xc423ad69c0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c34fd0 sp=0xc423c34e38 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x9056090ca955fc23, 0x7901469b7895b58c, 0x3b1562c0, 0xc42009adb0, 0x1, 0xc4220824e0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c35168 sp=0xc423c34fd0 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x793b16bb31b08e69, 0xec1dde688316907f, 0x2771a502, 0xc42009adb0, 0x1, 0xc4245cc060, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c35300 sp=0xc423c35168 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x596c948698372210, 0x80e79bd771a873f6, 0x4687ae4f, 0xc42009adb0, 0x1, 0xc423dd04c0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c35498 sp=0xc423c35300 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xa9af6368bae26316, 0x29526b28b384dd49, 0xa9da4900, 0xc42009adb0, 0x1, 0xc4245cc460, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c35630 sp=0xc423c35498 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x5c9dc965f5435ff3, 0x9f8d44820b21acbb, 0x7965c44, 0xc42009adb0, 0x1, 0xc423e74860, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c357c8 sp=0xc423c35630 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xf1fd881e68f500f3, 0x998fbb0c10398105, 0xc529500f, 0xc42009adb0, 0x1, 0xc423bfc440, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c35960 sp=0xc423c357c8 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x3ac0c13986472942, 0x55b64303ead3e76, 0xa13ee9f5, 0xc42009adb0, 0x1, 0xc421d52060, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c35af8 sp=0xc423c35960 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x3fbbcd4bfcea2bcc, 0xbac4044743c9b9a4, 0x47f1e030, 0xc42009adb0, 0x1, 0xc420e3a360, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c35c90 sp=0xc423c35af8 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xda9b8cbb49dd34da, 0x45b3d563f498bfb5, 0x9bdb7639, 0xc42009adb0, 0x1, 0xc421d522a0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c35e28 sp=0xc423c35c90 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x4f31d8448ea92b24, 0xa314969340d284b1, 0xdb24b4c9, 0xc42009adb0, 0x1, 0xc4246646a0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c35fc0 sp=0xc423c35e28 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x2dc732d068be2a1f, 0x35957112fd5a0c45, 0x8f25e696, 0xc42009adb0, 0x1, 0xc421f60360, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c36158 sp=0xc423c35fc0 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x1f214efc9a77556b, 0xf2a5819412c551f0, 0x6f38ea0, 0xc42009adb0, 0x1, 0xc421a26060, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c362f0 sp=0xc423c36158 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x47ae343ff1c373bd, 0x5b78bba47a7756b9, 0xe58e0791, 0xc42009adb0, 0x1, 0xc421e5c320, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c36488 sp=0xc423c362f0 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x7e1d3c43396eacf0, 0x9b1ed0a47a203993, 0x8a5ba0f7, 0xc42009adb0, 0x1, 0xc421a26100, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c36620 sp=0xc423c36488 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xd0b0334872dfb91f, 0x2c66a88c6effadf, 0xc7ac647, 0xc42009adb0, 0x1, 0xc42404a500, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c367b8 sp=0xc423c36620 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x90bcdb57e1a3f953, 0x376d34732cac021a, 0x8c97245e, 0xc42009adb0, 0x1, 0xc423c04280, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c36950 sp=0xc423c367b8 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x932cc340cec8f80b, 0xe4cc5ea4016c7de9, 0xabb24dd9, 0xc42009adb0, 0x1, 0xc42440e060, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c36ae8 sp=0xc423c36950 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xca41cc653a8927ea, 0x86586aaa660471d2, 0x1e2ff26f, 0xc42009adb0, 0x1, 0xc42201c1a0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c36c80 sp=0xc423c36ae8 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xf8656cfdf0aab2b3, 0x6cd977b16b635f3d, 0x139b0788, 0xc42009adb0, 0x1, 0xc42440ffa0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c36e18 sp=0xc423c36c80 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x6e77519fd6e756a8, 0xa7381f1f6f3d6340, 0xd5f064fd, 0xc42009adb0, 0x1, 0xc420e823a0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c36fb0 sp=0xc423c36e18 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xcd3a3dc1b07d99ac, 0xba95f09fc7b6fce8, 0x6971d26b, 0xc42009adb0, 0x1, 0xc4246261e0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c37148 sp=0xc423c36fb0 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x36b647fa7c4ab793, 0x31037dbc33b060c0, 0xe241789f, 0xc42009adb0, 0x1, 0xc420c70060, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c372e0 sp=0xc423c37148 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xcb3aefd970bb82fa, 0xc7b8ab3dfcd476a, 0x62c30aa4, 0xc42009adb0, 0x1, 0xc423c3c100, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c37478 sp=0xc423c372e0 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xa80c5c8d58400211, 0x598f0652da553b8d, 0x7d36d6d8, 0xc42009adb0, 0x1, 0xc420c71cc0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c37610 sp=0xc423c37478 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x23f8f5f3560aafeb, 0xb526d68fbc6641df, 0xdc64f823, 0xc42009adb0, 0x1, 0xc423dda0c0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c377a8 sp=0xc423c37610 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xe598878d0ec4fef3, 0x93ef3a27a9053f31, 0x9e51e42f, 0xc42009adb0, 0x1, 0xc420ddbde0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c37940 sp=0xc423c377a8 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x656844cf809e20f0, 0xdb5b4c1b8830773e, 0x9a38c75f, 0xc42009adb0, 0x1, 0xc423aec1e0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c37ad8 sp=0xc423c37940 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xda92206198e58e20, 0x4e0ddde8c0c12a89, 0x76f0c409, 0xc42009adb0, 0x1, 0xc424064100, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c37c70 sp=0xc423c37ad8 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xf46b40e57872b99e, 0xfc669435fae1e763, 0x269f85a9, 0xc42009adb0, 0x1, 0xc420eb4060, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c37e08 sp=0xc423c37c70 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x4fe4006c5d1cfa90, 0xdb1540cfa01d904c, 0x3ca6e91, 0xc42009adb0, 0x1, 0xc4244ec020, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c37fa0 sp=0xc423c37e08 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x5f69a9d00d7df202, 0xb5a297dd3d7c33a8, 0x73ec0aad, 0xc42009adb0, 0x1, 0xc420eb5c60, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c38138 sp=0xc423c37fa0 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xc12449dd363484ed, 0x50af3dc70c826906, 0xbddab4f0, 0xc42009adb0, 0x1, 0xc423fe2060, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c382d0 sp=0xc423c38138 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x87416103697209a9, 0x371a56eede6d586c, 0xe5c886b6, 0xc42009adb0, 0x1, 0xc424186040, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c38468 sp=0xc423c382d0 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x94dc95f59cff6380, 0x10ae10337da2e714, 0x83c8f531, 0xc42009adb0, 0x1, 0xc421ee0060, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c38600 sp=0xc423c38468 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x13a19acec03d8f07, 0xb4119c5eebcf77ce, 0xfe7da9ea, 0xc42009adb0, 0x1, 0xc421fbdf60, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c38798 sp=0xc423c38600 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x38d57234c3bbe192, 0x58da379df333599d, 0x5330e0e7, 0xc42009adb0, 0x1, 0xc421ee1b20, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c38930 sp=0xc423c38798 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x69cac7b1d561368d, 0xc68858a02536868a, 0xc1d30460, 0xc42009adb0, 0x1, 0xc423eb1f20, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c38ac8 sp=0xc423c38930 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xac20d962e737900, 0xe33d59d54380a6b2, 0x7f37f158, 0xc42009adb0, 0x1, 0xc423e49fa0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c38c60 sp=0xc423c38ac8 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x9b83600885dab85e, 0x87b89e0780ab38df, 0x3144765b, 0xc42009adb0, 0x1, 0xc424440060, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c38df8 sp=0xc423c38c60 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x1c44615159d9a26d, 0x46ddb879f5b1d1be, 0x208e0a97, 0xc42009adb0, 0x1, 0xc423d45ec0, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c38f90 sp=0xc423c38df8 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x6a6f40bf34444018, 0xcfc52033d72e896f, 0xdd87c19c, 0xc42009adb0, 0x1, 0xc424441920, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c39128 sp=0xc423c38f90 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0xcdb71a637b2422cf, 0x843f5817992801fe, 0x326feadf, 0xc42009adb0, 0x1, 0xc423a97d20, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c392c0 sp=0xc423c39128 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x423ebe57bf2a5d08, 0xe47fc2c87d0bad4c, 0x8e252119, 0xc42009adb0, 0x1, 0xc423b49e40, 0x0, 0x1, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c39458 sp=0xc423c392c0 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.ancestors(0x2fa22df1581733e3, 0x30b5e1efc7ee0341, 0xe9e59b4a, 0xc42009adb0, 0x13353d4, 0x6, 0xe9e59b4a, 0x1377b80, 0xc4200b40e0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:357 +0x43c fp=0xc423c395f0 sp=0xc423c39458 pc=0x1264d3c
github.com/driusan/dgit/git.CommitID.Ancestors(0x2fa22df1581733e3, 0x30b5e1efc7ee0341, 0xe9e59b4a, 0xc42009adb0, 0x2fa22df1581733e3, 0x30b5e1efc7ee0341, 0xc4e9e59b4a, 0x0, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:303 +0x5a fp=0xc423c396a0 sp=0xc423c395f0 pc=0x126475a
github.com/driusan/dgit/git.ParsedRevision.Ancestors(0x2fa22df1581733e3, 0x30b5e1efc7ee0341, 0xe9e59b4a, 0xc42009adb0, 0xc4200d2380, 0x1, 0x1, 0x0, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/revparse.go:47 +0xd9 fp=0xc423c39720 sp=0xc423c396a0 pc=0x12611e9
github.com/driusan/dgit/cmd.RevList(0xc42009adb0, 0xc42009a0b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x3, 0x5)
	/Users/cmcgee/go/src/github.com/driusan/dgit/cmd/rev-list.go:65 +0x8f5 fp=0xc423c39b28 sp=0xc423c39720 pc=0x128c0c5
main.main()
	/Users/cmcgee/go/src/github.com/sirnewton01/dgit/main.go:179 +0x868 fp=0xc423c39f88 sp=0xc423c39b28 pc=0x1291e78
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc423c39fe0 sp=0xc423c39f88 pc=0x102c472
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc423c39fe8 sp=0xc423c39fe0 pc=0x1055e81

rax    0x4
rbx    0x0
rcx    0xc423c33b70
rdx    0x0
rdi    0x3
rsi    0xc423a50f38
rbp    0xc423c33bc8
rsp    0xc423c33b70
r8     0x0
r9     0x0
r10    0x0
r11    0x206
r12    0xf4
r13    0xf3
r14    0x200
r15    0x1054c10
rip    0x1073e76
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

I have attached the git repository that exhibits the problem.
[badrepo2.zip](https://github.com/driusan/dgit/files/2180654/badrepo2.zip)

**Comment by sirnewton01** [comment]
It appears to be a corrupt git repository in this case. The standard git client just bails right away. It might be nice to be more robust and detect it rather than hanging.

**Comment by sirnewton01** [comment]
This is happening when you run make t0*.sh in the standard git test suite.

**Comment by driusan** [comment]
It comes from the t0002-gitfile.sh test, which is explicitly testing against invalid .git directories.. so it seems the test is working.

**Comment by sirnewton01** [comment]
I'm not seeing this error on the official git 2.8.0 tag. It seems that the test case is new.
