### ISSUE TITLE
Infinite recursion when running git merge origin/master

### ISSUE THREAD

**Issue by sirnewton01** [driusan/dgit#99]
While running ```dgit merge origin/master``` an infinite recursion happens. Here is a snippet of the stack trace from kill -ABRT:

```
goroutine 1 [runnable]:
syscall.Syscall(0x3, 0x5, 0xc4203be000, 0x14, 0x14, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x5, 0xc4203be000, 0x14, 0x14, 0xc4200ac401, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:947 +0x5f
syscall.Read(0x5, 0xc4203be000, 0x14, 0x14, 0x14, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:162 +0x49
internal/poll.(*FD).Read(0xc4200b4d20, 0xc4203be000, 0x14, 0x14, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:153 +0x116
os.(*File).read(0xc4200b2080, 0xc4203be000, 0x14, 0x14, 0x7, 0x2259488, 0x1050940)
	/usr/local/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc4200b2080, 0xc4203be000, 0x14, 0x14, 0x14, 0xc4203be000, 0x0)
	/usr/local/go/src/os/file.go:107 +0x6a
io.ReadAtLeast(0x13961e0, 0xc4200b2080, 0xc4203be000, 0x14, 0x14, 0x14, 0x12e1be0, 0x1317401, 0xc4203be000)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x13961e0, 0xc4200b2080, 0xc4203be000, 0x14, 0x14, 0x14, 0x0, 0x0)
	/usr/local/go/src/io/io.go:327 +0x58
encoding/binary.Read(0x13961e0, 0xc4200b2080, 0x139a7e0, 0x151f3b0, 0x1311ba0, 0xc42042f958, 0x0, 0x0)
	/usr/local/go/src/encoding/binary/binary.go:245 +0xf48
github.com/driusan/dgit/git.getPackFileObject(0x13961e0, 0xc4200b2080, 0x13984e0, 0xc4200b2088, 0x6d54d16fc180d95e, 0x8edd5d6f707675dc, 0x7e4d142e, 0xc4205460c0, 0x1012368, 0x20, ...)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/indexpack.go:235 +0x2c2
github.com/driusan/dgit/git.(*Client).getPackedObject(0xc4200ac300, 0xc4200c6400, 0x6f, 0x6d54d16fc180d95e, 0x8edd5d6f707675dc, 0xc47e4d142e, 0x0, 0x0, 0x0, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/objects.go:156 +0x1a0
github.com/driusan/dgit/git.(*Client).GetObject(0xc4200ac300, 0x6d54d16fc180d95e, 0x8edd5d6f707675dc, 0xc47e4d142e, 0x0, 0x0, 0x0, 0x0)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/objects.go:179 +0xe25
github.com/driusan/dgit/git.CommitID.Parents(0x6d54d16fc180d95e, 0x8edd5d6f707675dc, 0xc47e4d142e, 0xc4200ac300, 0xc420546600, 0x1270c3f, 0xc4201de230, 0x1, 0x8)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:117 +0x5d
github.com/driusan/dgit/git.CommitID.AncestorMap(0x6d54d16fc180d95e, 0x8edd5d6f707675dc, 0xc47e4d142e, 0xc4200ac300, 0xc420186360, 0x1, 0x1)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:170 +0xcc
github.com/driusan/dgit/git.CommitID.AncestorMap(0xb52dd8645c105354, 0xe535f57c73b0a6cd, 0xc4edeef6f1, 0xc4200ac300, 0xc42013d240, 0x1, 0x1)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:183 +0x320
github.com/driusan/dgit/git.CommitID.AncestorMap(0x3e4bf91df946be93, 0xbd5a7dac21cf95c4, 0xc459574d96, 0xc4200ac300, 0xc4204b5d40, 0x1, 0x1)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:183 +0x320
github.com/driusan/dgit/git.CommitID.AncestorMap(0x2c217e3b3c7f732c, 0x853dff90415dfec5, 0xc4926fffd8, 0xc4200ac300, 0xc42031a700, 0x1, 0x1)
	/Users/cmcgee/go/src/github.com/driusan/dgit/git/sha1.go:183 +0x320
github.com/driusan/dgit/git.CommitID.AncestorMap(0xe7ff12d06c934b81, 0x47e9eacc3e7a30a0, 0xc4f19d43c8, 0xc4200ac300, 0xc4204c8e00, 0x1, 0x1)
```

Note that if I run git merge origin the following error occurs:
read /Users/cmcgee/go/src/github.com/golang/protobuf/.git/refs/remotes/origin: is a directory

It should probably return a friendlier message:
merge: origin - not something we can merge

**Comment by sirnewton01** [comment]
If I run this same command against another repo I get this error:

```
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/driusan/dgit/git.PackfileIndexV2.HasObject(0x2634f74ff, 0x0, 0x0, 0x200000002, 0x500000005, 0x700000006, 0x900000009, 0xa00000009, 0xa0000000a, 0xa0000000a, ...)
	/home/travis/gopath/src/github.com/driusan/dgit/git/indexpack.go:308 +0x100
github.com/driusan/dgit/git.v2PackIndexHasSha1(0xc4200a0300, 0xc4201f4200, 0x75, 0x795320, 0xc4200a71a0, 0x0, 0x0, 0xc400000000, 0x79)
	/home/travis/gopath/src/github.com/driusan/dgit/git/indexpack.go:86 +0x304
github.com/driusan/dgit/git.(*Client).HaveObject(0xc4200a0300, 0x0, 0x0, 0x0, 0x43, 0x7c0000007c, 0x7c0000007c, 0x7c0000007c, 0x7d0000007d)
	/home/travis/gopath/src/github.com/driusan/dgit/git/client.go:466 +0x74d
github.com/driusan/dgit/git.(*Client).GetObject(0xc4200a0300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/driusan/dgit/git/objects.go:168 +0x9b
github.com/driusan/dgit/git.(*Client).GetCommitObject(0xc4200a0300, 0x0, 0x0, 0x0, 0x7f872ca2df78, 0x450a90, 0x7f872ca286c8, 0xc42000012c, 0xc42021ca00, 0x411479)
	/home/travis/gopath/src/github.com/driusan/dgit/git/objects.go:160 +0x5a
github.com/driusan/dgit/git.CommitID.TreeID(0x0, 0x0, 0xc400000000, 0xc4200a0300, 0x0, 0x0, 0x0, 0xc420044c00, 0x40e31d)
	/home/travis/gopath/src/github.com/driusan/dgit/git/sha1.go:502 +0x66
github.com/driusan/dgit/git.expandGitTreeIntoIndexes(0xc4200a0300, 0x795dc0, 0xc4201e2880, 0x1, 0x708f20, 0xc4200907b0, 0xc4201f24d0, 0xb, 0xc420093e98)
	/home/travis/gopath/src/github.com/driusan/dgit/git/expandtree.go:21 +0x56
github.com/driusan/dgit/git.GetIndexMap(0xc4200a0300, 0x795dc0, 0xc4201e2880, 0x0, 0x0, 0x6f3d60)
	/home/travis/gopath/src/github.com/driusan/dgit/git/sha1.go:523 +0x58
github.com/driusan/dgit/git.ReadTreeThreeWay(0xc4200a0300, 0x10001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x795dc0, ...)
	/home/travis/gopath/src/github.com/driusan/dgit/git/readtree.go:89 +0xd2
github.com/driusan/dgit/git.Merge(0xc4200a0300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42008ac30, ...)
	/home/travis/gopath/src/github.com/driusan/dgit/git/merge.go:151 +0x60f
github.com/driusan/dgit/cmd.Merge(0xc4200a0300, 0xc42009e130, 0x1, 0x1, 0x1, 0x0)
	/home/travis/gopath/src/github.com/driusan/dgit/cmd/merge.go:43 +0x491
main.main()
	/home/travis/gopath/src/github.com/driusan/dgit/main.go:210 +0x3225
```

**Comment by driusan** [comment]
What was the state of the repo and what were you trying to merge? Is this a fast-forward or a 3-way merge? Would it be possible to turn this into a `go test` test case?

**Comment by sirnewton01** [comment]
@driusan it's just a fast forward. I adjust the go-get-tests.sh to try fetch + merge of different repos that where checkout HEAD^1 was done to them to approximate what the new git pull would do.

**Comment by driusan** [comment]
Can you see if#104 helps? It's more of a hack than a fix, but I was able to checkout github.com/sirnewton01/gdblib HEAD^ and merge origin/master with it. (I wasn't getting an infinite loop though, I was getting other problems)

**Comment by sirnewton01** [comment]
#104 seems to fix the problems with both repos. Thanks. I'll keep plodding along with pull.
